### PR TITLE
Address zero-sized downloads

### PR DESCRIPTION
**Pull request by EricTheMagician**
This PR: 
- addresses the zero size detection described in #7 using requests  to download files instead of wget

### CODE REVIEW

**Comment by Cameron-IPFSPodcasting** [comment]
I'm not sure how ifne will prevent and/or return an error code for a zero sized file (I haven't tested either). 

Currently [error code "99"](https://github.com/Cameron-IPFSPodcasting/podcastnode-Python/blob/6701d7ccdbfab6fc59b5c7c91f5a850a4f26181a/ipfspodcastnode.py#L138) means pinning failed/timed out in the [payload["error"]](https://github.com/Cameron-IPFSPodcasting/podcastnode-Python/blob/6701d7ccdbfab6fc59b5c7c91f5a850a4f26181a/ipfspodcastnode.py#L160C15-L160C15) response.

"98" for a pinning error/timeout

"97" for a zero sized file? 

I'd like it to report an error in the response, so the website can compare responses from multiple nodes (i.e. if multiple nodes report the same error (for the same file/enclosure), I can flag the item to prevent sending to more nodes.

**Comment by EricTheMagician** [comment]
The return code would have been the return code of wget, if it errored out: https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html

When I tried `ifne`, I got exit code `8` when I tried a page that I know returns a 404 error page. 

Another option, we could forego `wget` entirely and just use python's request library and pipe the response directly to the ipfs stdin pipe.

**Comment by Cameron-IPFSPodcasting** [comment]
Ok. I'll have to test.

This was a url that gave me a 410 https://dl.iono.fm/epi/prov_8/epi_1321013_medium.m4a?p=rss
This was a 404 https://dl.iono.fm/epi/prov_8/epi_1314717_medium.m4a?p=rss
(both from Deutsche Welle)

In the beginning, I tried a python ipfs api (ipfshttpclient), but couldn't get it working. It looks like there's something new https://pypi.org/project/IPFS-Toolkit/ A lot more work, but I should look at it again.

**Comment by EricTheMagician** [comment]
I was thinking more something like:

```python
import requests
import subprocess
url = '...' 

response = requests.get(url, stream=True)

if response.ok:
  p = subprocess.Popen([ipfspath,'add',  '-q', '-w', '--stdin-name', work['filename']], 
                       stdin=subprocess.PIPE, 
                       stdout=subprocess.PIPE)

  for chunk in response.iter_content(1024):
    p.stdin.write(chunk)
  p.stdin.close()
  output = p.stdout.read()
```

**Comment by Cameron-IPFSPodcasting** [comment]
Whatever works : ) The code is 2-3 years old. I'm sure it could use some optimization.

Was seeing weird sizes with Ryan based on the download method. https://podcastindex.social/@cameron/111087328082426434 Maybe this will fix something(?)

Have to compare with the other nodes (Umbrel, Start9, etc.) so everyone is getting the same result. Don't worry about the other flavors, until this repo/version is working.

**Comment by EricTheMagician** [comment]
I get a page 404 on that link to mastodon

**Comment by Cameron-IPFSPodcasting** [comment]
Sorry, I just noticed that was a private thread. Just some messages about failing to download the same file. Ryan Hirsch build a nodejs client and was having problems generating the same hash with his download method, while I (and other nodes) always got the same data from multiple locations (not DAI). Here's his repo for a node based ipfspodcast client. https://github.com/RyanHirsch/ptk-ipfs

**Comment by EricTheMagician** [comment]
I'm not too familiar with NodeJS / Typescript, but I'll check it out later.

I've started replacing `wget` with python's `requests`.  Can you check server side if everything is ok? The client would be 0.7p, but it just seems like it's just downloading from source at the moment instead of downloading from ipfs.

Also, do you have a minimum python version in mind that you want to support?
I want to use the string interpolation feature from python 3.8.

**Comment by Cameron-IPFSPodcasting** [comment]
Are you mixing versions on your current node? I see requests from 0.6z, then 0.7p, then 0.6z coming from the same IPFS ID. It might be confusing requests/versions. Try turning off 0.6z, so you're only requesting 0.7p.

It will only download from IPFS when there are 5+ copies in IPFS. Try gold favoriting a feed with more than 5 other nodes. I'd suggest https://ipfspodcasting.net/Feed/448/PodnewsDaily-podcastingnews Small episodes with ~50 nodes pinning. 

A newly published show will always download from the source (until 5 nodes have a copy).

Python 3.8 is OK. Whatever the leading distros use. When I build a docker (Umbrel/Start9), I usually grab the latest.

**Comment by Cameron-IPFSPodcasting** [comment]
Should I merge this PR, or are you still making changes?

**Comment by EricTheMagician** [comment]
If things are looking good on the backend, it's good to go now.
I swapped the order of the ckeck for no work to bring it up to the top. It's just to make it clear and a "quick return" for when  turbo mode is implemeneted.

**Comment by Cameron-IPFSPodcasting** [comment]
I see a 0.7z node now. Seems to be working. Is the version a typo (0.7p), or are you updating your nix code?

**Comment by EricTheMagician** [comment]
I used both 0.7 p and z.
The p was while I was running it standalone to make sure that it was working.
The z was when I deployed it properly in my nix system.
And there was small time where it was deployed as 0.7p because I forgot to update the command that replaces the p with a z in my build script for nix.

If you see more 0.7p in the future coming from my node, it's because I'm running it outside of nix to test things. Like turbo mode., though I don't think I will get to it this week.

**Pull request merged**
